language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install numpy"
  - "pip install scipy"
  - "pip install sklearn"
  - "pip install pymongo"
# command to run tests
script: nosetests
