language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install numpy"
#  - "pip install scipy"
#  - "pip install sklearn"
  - "pip install pymongo"
  - "pip install flask"
  - "pip install psycopg2"
# command to run tests
script: nosetests

# A nudge to avoid checking in broken builds.
notifications:
  email:
    on_success: never
    on_failure: always
