#!/usr/bin/env python3
import sys
import random

s = 'All work and no play makes Jack a dull boy'
l = len(s)
f = sys.stdout
for _ in range(0,100000):
  r = random.randint(0,5)
  i = random.randint(1,l-2)
  c = random.choice('abcdefghijklmnopqrstuvwxyz')
  if r==0: # swap
    print(s[0:i-1]+s[i+1]+s[i]+s[i+1:], file=f)
  elif r==1: # drop
    print(s[0:i-1]+s[i:], file=f)
  elif r==2: # insert
    print(s[0:i]+c+s[i:], file=f)
  elif r==3: # replace
    print(s[0:i-1]+c+s[i:], file=f)
  else: # normal
    print(s, file=f)
